name: google_flutter_health_example
description: Example app for the google_flutter_health package.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  google_flutter_health:
    path: ../
  flutter_secure_storage: ^10.0.0
  google_sign_in: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
