name: google_flutter_health
description: >-
  A Flutter package to make your life easier when dealing with
  the Google Health API. The spiritual successor to Fitbitter.
version: 0.6.0
homepage: https://github.com/DFerrari13/google_flutter_health
repository: https://github.com/DFerrari13/google_flutter_health
issue_tracker: https://github.com/DFerrari13/google_flutter_health/issues

topics:
  - health
  - fitness
  - google-health
  - flutter
  - wearable

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0
  test: ^1.25.8
